# Generated by Django 6.0.7 on 2026-07-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quizquestion_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
